- src/main/java/com/hanhwa_tae/gulhan/common/dto/ApiResponse.java
- src/main/java/com/hanhwa_tae/gulhan/common/dto/exam.java
feat/common -> dev
Controller에서 사용할 응답 ApiResponse 클래스 생성
close #11
> Feat: ApiResponse 파일 생성 

- build.gradle
- src/main/java/com/hanhwa_tae/gulhan/common/dto/ApiResponse.java
- src/main/java/com/hanhwa_tae/gulhan/common/dto/exam.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
- src/main/java/com/hanhwa_tae/gulhan/utils/EmailUtil.java
- src/main/resources/application.yml
ex) feat/user-email-> feat/user-jwt 
유저 이메일 전송 기능 완성했습니다!
- utils/EmailUtils 클래스를 통해 Email 전송 구현
- UUID 형태로 인증 코드 전송
close #14
> Feat/user-email 이메일 전송 기능 완성

- src/main/java/com/hanhwa_tae/gulhan/common/exception/BusinessException.java
- src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
- src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorResponse.java
- src/main/java/com/hanhwa_tae/gulhan/common/exception/GlobalExceptionHandler.java
- src/main/java/com/hanhwa_tae/gulhan/common/exception/exam.java
ex) feat/exception -> dev
- 글로벌 예외 처리 코드 추가
close #24
> feat: 에러코드 생성 및 에러코드 기입 

- src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/UserCreateDTO.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/UserCreateRequest.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/User.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/UserInfoResponse.java
ex) fix/user-entity -> dev
유저 엔티티의 유저 명 수정
- userName -> username
> fix: 유저 엔티티 username 변경

- src/main/java/com/hanhwa_tae/gulhan/place/command/domain/aggregate/CategoryType.java
- src/main/java/com/hanhwa_tae/gulhan/place/command/domain/aggregate/Place.java
- src/main/java/com/hanhwa_tae/gulhan/place/exam.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/controller/AreaQueryController.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/controller/PlaceQueryController.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/dto/request/AreaSearchRequest.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/dto/request/PlaceSearchRequest.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/AreaDto.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/AreaListResponse.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/PlaceDto.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/PlaceListResponse.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/mapper/AreaMapper.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/mapper/PlaceMapper.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/service/AreaQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/service/PlaceQueryService.java
- src/main/resources/mappers/area/AreaMapper.xml
- src/main/resources/mappers/place/PlaceMapper.xml
feat/placeselect -> dev
* 조건별 장소 검색 기능 구현(시, 도, 지역 명, 장소 이름)
* 지역 목록 조회 API 구현
close #29 #22
> feat: 조건별 장소 검색 기능 구현, 지역 목록 조회 기능 구현

- src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/service/PlaceQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/ChangeUserPasswordRequest.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
- src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserRepository.java
feat/change-password -> dev
인증된 회원에 대한 비밀번호 변경 요청을 구현했습니다!
closes #76
> feat: 비밀번호 변경 구현

- src/main/java/com/hanhwa_tae/gulhan/goods/command/application/controller/GoodsCommandController.java
- src/main/java/com/hanhwa_tae/gulhan/goods/command/application/controller/examp.java
- src/main/java/com/hanhwa_tae/gulhan/goods/command/application/service/GoodsCommandService.java
- src/main/java/com/hanhwa_tae/gulhan/goods/command/application/service/examp.java
- src/main/java/com/hanhwa_tae/gulhan/goods/command/domain/aggregate/Goods.java
- src/main/java/com/hanhwa_tae/gulhan/goods/command/domain/aggregate/GoodsCategory.java
- src/main/java/com/hanhwa_tae/gulhan/goods/command/domain/repository/JpaGoodsRepository.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/controller/GoodsQueryController.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/controller/examp.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/dto/request/GoodsInsertRequest.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/dto/request/GoodsSearchRequest.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/dto/request/GoodsUpdateRequest.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/dto/request/examp.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/dto/response/GoodsDTO.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/dto/response/GoodsListResponse.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/dto/response/examp.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/mapper/GoodsMapper.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/mapper/examp.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/service/GoodsQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/goods/query/service/examp.java
- src/main/java/com/hanhwa_tae/gulhan/packages/query/dto/request/PackageSearchRequest.java
- src/main/java/com/hanhwa_tae/gulhan/packages/query/dto/response/PackageDTO.java
- src/main/java/com/hanhwa_tae/gulhan/packages/query/service/PackageQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/place/query/service/PlaceQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/review/command/application/controller/ReviewCommandController.java
- src/main/java/com/hanhwa_tae/gulhan/review/command/application/service/ReviewCommandService.java
- src/main/java/com/hanhwa_tae/gulhan/review/query/mapper/OrderMapper.java
- src/main/resources/mappers/goods/GoodsMapper.xml
- src/main/resources/mappers/packages/PackageMapper.xml
- src/main/resources/mappers/review/OrderMapper.xml
feat/goods -> dev
조회/등록/수정/삭제 테스트 완료
close #68
> feat: 기념품 조회/등록/수정/삭제 

- src/main/java/com/hanhwa_tae/gulhan/cart/command/domain/aggregate/Order.java
- src/main/java/com/hanhwa_tae/gulhan/dashboard/command/application/dto/request/OrderUpdateRequest.java
- src/main/java/com/hanhwa_tae/gulhan/dashboard/command/application/service/DashboardCommandService.java
- src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/OrderAllListDTO.java
- src/main/resources/mappers/dashboard/DashboardMapper.xml
feat/dashboard -> dev
패키지 별 판매 수량 조회
기념품 별 판매 수량 조회
월별 판매 수익
일별 판매 수익
운송장 번호가 입력되지 않은 주문내역 조회
운송장 번호 입력
테스트완료
> Feat/dashboard : 대시보드 구현

- src/main/java/com/hanhwa_tae/gulhan/travelmatepost/command/domain/aggregate/Comment.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/controller/UserQueryController.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/dto/UserReviewDTO.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/RankDTO.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/UserCommentDTO.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/UserCommentResponse.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/UserReviewDTO.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/UserReviewResponse.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryServiceImpl.java
- src/main/resources/mappers/user/UserMapper.xml
ex) feat/mypage -> dev
- 내가 쓴 리뷰 조회
- 내가 쓴 댓글 조회
closes #90
closes #91 
closes #93
> feat: 유저 작성 댓글, 리뷰 조회

- src/main/java/com/hanhwa_tae/gulhan/user/me/query/controller/MyPageQueryController.java
- src/main/java/com/hanhwa_tae/gulhan/user/me/query/mapper/MyPageMapper.java
- src/main/java/com/hanhwa_tae/gulhan/user/me/query/service/MyPageQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/controller/UserQueryController.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryService.java
- src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryServiceImpl.java
- src/main/resources/mappers/user/UserMapper.xml
- src/main/resources/mappers/user/me/MyPageMapper.xml
refactor/me -> dev
`/mypage` 엔드포인트와 `/me` 엔드포인트를 `/me`로 통일
> refactor: /myPage /me 코드 통일

- src/main/java/com/hanhwa_tae/gulhan/user/me/query/controller/MyPageQueryController.java
- src/main/java/com/hanhwa_tae/gulhan/user/me/query/dto/GoodsOrderHistoryDTO.java
- src/main/java/com/hanhwa_tae/gulhan/user/me/query/mapper/MyPageMapper.java
- src/main/java/com/hanhwa_tae/gulhan/user/me/query/service/MyPageQueryService.java
- src/main/resources/mappers/user/UserMapper.xml
- src/main/resources/mappers/user/me/MyPageMapper.xml
feat/user-orderhistory -> dev
패키지/기념품 구매내역 조회 수정
> fix: 패키지/기념품 구매내역 조회 수정

- src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
- src/main/java/com/hanhwa_tae/gulhan/config/SecurityConfig.java
- src/main/java/com/hanhwa_tae/gulhan/utils/jwt/CustomAuthenticationEntryPoint.java
- src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtAuthenticationFilter.java
- src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtTokenProvider.java
ex) feat/security-> dev
closes #101
- Spring Security 인증/인가 설정
- Filter에서 발생하는 에러 Custom 설정
> feat: Spring Config 설정

- src/main/resources/mappers/user/me/MyPageMapper.xml
feat/update-mypage -> dev
is_confirmed 컬럼 수정 반영
> fix: MyPageMapper 쿼리 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/application/controller/DashboardCommandController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/application/dto/request/OrderUpdateRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/application/dto/response/examp.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/application/service/DashboardCommandService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/mapper/DashboardOrderMapper.java
- second-server/src/main/resources/mappers/dashboard/DashboardMapper.xml
- second-server/src/main/resources/mappers/dashboard/DashboardOrderMapper.xml
fix/dashboard -> settings/msa
기존 jpa를 사용해서 구현 한 내용 mybatis로 변경
테스트 완료
> Fix: 대시보드 운송장번호 입력 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/config/SwaggerConfig.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/annotation/WithCustomMockUser.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/user/command/application/controller/UserCommandControllerTest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/user/query/controller/UserQueryControllerTest.java
ex) test/user -> settings/msa
closes #113
user domain의 controller에 대한 테스트 코드를 추가했습니다!
> feat: user/controller 테스트 코드 작성

- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/application/dto/request/OrderUpdateRequest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/annotation/WithCustomMockAdmin.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/annotation/WithCustomMockUser.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/annotation/factory/WithCustomMockAdminFactory.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/dashboard/command/application/controller/DashboardCommandControllerTest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/dashboard/query/controller/DashboardQueryControllerTest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/user/command/application/controller/UserCommandControllerTest.java
test/dashboard -> settings/msa
controller 테스트 코드 작성
정상적으로 테스트 완료
> Test: 대시보드 테스트 구현 

- second-server/src/main/java/com/hanhwa_tae/secondserver/travelmatepost/command/application/dto/request/CommentUpdateRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/travelmatepost/command/application/dto/request/TmpInsertRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/travelmatepost/command/application/dto/request/TmpUpdateRequest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/travelmatepost/command/application/controller/CommentCmdControllerTest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/travelmatepost/command/application/controller/TpmCmdControllerTest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/travelmatepost/query/controller/CommentQueryControllerTest.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/travelmatepost/query/controller/TmpQueryControllerTest.java
test/travelmatepost -> settings/msa
동행글 및 댓글 테스트 코드 작성
테스트 완료입니다.
> Test: 동행글 테스트 구현

- second-server/src/test/java/com/hanhwa_tae/secondserver/auth/query/controller/AuthQueryControllerTest.java
test/auth -> settings/msa
auth 테스트 코드 추가했습니다!
> test: auth 테스트 코드 작성

- first-server/src/main/java/com/hanhwa_tae/firstserver/place/query/dto/request/AreaSearchRequest.java
- first-server/src/test/java/com/hanhwa_tae/firstserver/place/query/controller/AreaQueryControllerTest.java
- first-server/src/test/java/com/hanhwa_tae/firstserver/place/query/controller/PlaceQueryControllerTest.java
test/place -> settings/msa
테스트 완료
> test: 장소 테스트

- first-server/src/main/java/com/hanhwa_tae/firstserver/place/query/dto/request/AreaSearchRequest.java
- first-server/src/test/java/com/hanhwa_tae/firstserver/place/query/controller/AreaQueryControllerTest.java
test/areas -> settings/msa
테스트 완료
> test: 지역 목록 검색 테스트

- second-server/src/test/java/com/hanhwa_tae/secondserver/dashboard/command/application/controller/DashboardCommandControllerTest.java
ex) test/auth -> settings/msa
dashboard 테스트 코드 복구
> fix: dashboard 테스트 코드 복구

- first-server/src/main/java/com/hanhwa_tae/firstserver/common/exception/ErrorCode.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/goods/command/domain/repository/JpaGoodsRepository.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/like/command/application/service/LikeCommandService.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/packages/command/domain/repository/JpaPackageRepository.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/place/command/domain/repository/PlaceRepository.java
fix/like -> settings/msa2
좋아요 시 해당 타겟이 없으면 해당 타겟이 존재하지 않는다고 뜸
> fix: 좋아요 기능 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/auth/command/application/service/KakaoAuthProvider.java
feat/user-kakao -> settings/msa2
url 수정
> fix: 카카오 url 수정

- second-server/build.gradle
- second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/ErrorCode.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/controller/DeliveryQueryController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/controller/examp.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/dto/request/DeliveryInfoRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/service/DeliveryQueryService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/security/SecurityConfig.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/DeliveryStateCode.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/TrackResponse.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/response/DeliveryStateResponse.java
- second-server/src/test/java/com/hanhwa_tae/secondserver/delivery/query/service/DeliveryQueryServiceTest.java
ex) feat/delivery -> main
배송 현황 조회 구현 했습니다.
현재는 배송사, 운송장 번호로 조회하지만 추후 order_id를 통해 해당 정보를 가져오도록 수정해야 합니다!
closes #141
> feat: 배송 현황 조회

- second-server/build.gradle
- second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/ErrorCode.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/GlobalExceptionHandler.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/notice/command/application/controller/NoticeCommandController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/annotation/ValidPassword.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/annotation/ValidUserId.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/controller/UserCommandController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserCreateRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserFindPasswordRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserVerifyFindPasswordRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/domain/aggregate/RedisUserPassword.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/infrastructure/RedisUserPasswordRepository.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/validator/PasswordValidator.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/validator/UserIdValidator.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/utils/EmailUtil.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/utils/image/controller/ImageController.java
> fix: 유저 기능 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/travelmatepost/command/application/service/CommentCmdService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/travelmatepost/command/application/service/TmpCmdService.java
fix/travelmatepost -> main
관리자가 모든 동행글 및 댓글 삭제 가능하게 구현했습니다.
포스트맨 테스트 통과
> Fix: 동행글 & 댓글 수정

- second-server/build.gradle
- second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/ErrorCode.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/config/AwsConfig.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/controller/ImageController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/service/ImageService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/service/ImageServiceImpl.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserCreateRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/utils/FileUtil.java
ex) fix/signup-> dev
회원가입 약관동의 로직 수정
> fix: 회원가입 로직 수정 

- second-server/src/main/java/com/hanhwa_tae/secondserver/image/controller/ImageController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/dto/response/ImageUploadResponse.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/service/ImageService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/service/ImageServiceImpl.java
ex) feat/image -> main
이미지 임시 저장 구현
이미지 를 s3 temp 폴더에 임시 저장하고, cloudfront를 거친  url을 응답합니다!
> feat: 이미지 임시 저장

- .idea/dataSources.local.xml
- .idea/dataSources.xml
- first-server/src/main/java/com/hanhwa_tae/firstserver/goods/command/domain/aggregate/Goods.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/packages/query/dto/response/PackageDTO.java
refactor/packages -> main
DTO에 좋아요 수와 리뷰 수를 추가하였습니다.
완료
> refactor: DTO에 좋아요수, 리뷰수 추가

- second-server/src/main/java/com/hanhwa_tae/secondserver/security/SecurityConfig.java
ex) feat/image-> main
이미지 업로드 시 발생한 cors 에러 auth 서버 만 해결
> fix: 이미지업로드 auth 서버 cors에러 고침

- first-server/src/main/java/com/hanhwa_tae/firstserver/cart/command/application/service/OrderCommandService.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/controller/SuccessFailController.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/controller/TossPaymentController.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/dto/request/CancelRequestDto.java
- first-server/src/main/resources/mappers/user/userMapper.xml
- first-server/src/main/resources/templates/widget/checkout.html
- first-server/src/main/resources/templates/widget/success.html
- gateway/build.gradle
- gateway/src/main/resources/application.yml
- second-server/hs_err_pid7480.log
- second-server/src/main/java/com/hanhwa_tae/secondserver/security/SecurityConfig.java
ex) feat/refactor -> main
1. 결제 로직 수정
2. gateway 설정 수정 -> circuitbreaker 주석 처리
테스트 완료 했습니다.
> Refactor: 결제 로직 수정 및 gateway 설정 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/application/controller/DeliveryCommandController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/application/dto/request/DeliveryAddressRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/application/service/DeliveryCommandService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/domain/aggregate/DeliveryAddress.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/domain/repository/DeliveryAddressRepository.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/controller/DeliveryQueryController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/dto/request/examp.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/dto/response/examp.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/service/DeliveryQueryService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/service/examp.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/me/query/controller/MyPageQueryController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/me/query/mapper/MyPageMapper.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/me/query/service/MyPageQueryService.java
- second-server/src/main/resources/mappers/user/me/MyPageMapper.xml
feat/delivery-address -> dev
마이페이지 배송지 목록 조회를 구현했습니다.
포스트맨 테스트 통과
> feat: 마이페이지 배송지 목록 조회

- .idea/dataSources.local.xml
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/domain/aggregate/DefaultAddress.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/dto/response/DeliveryAddressDTO.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/dto/response/DeliveryAddressResponse.java
ex) feat/delivery-address-> main
기본 배송지 enum 파일 추가
> feat: 기본배송지 enum 파일 업로드

- gateway/src/main/resources/application.yml
- second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/ErrorCode.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/security/SecurityConfig.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/controller/UserCommandController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserCreateRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
ex) fix/user-> main
**1. cors 수정**
gateway에서 왠지 모르게 cors에러가 발생해서 cors 설정을 각 서버에서 게이트웨이 쪽으로 옮겼습니다! yaml 파일에 설정 정보 확인해주시면 될 것 같아요!
**2. 회원가입 로직 수정**
회원가입 성공, 실패 시 페이지를 프론트에 만들어 리다이렉션 하도록 설정하였습니다!
> fix: 회원가입 로직 수정, cors 적용

- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UpdateUserInfoRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/validator/PhoneValidator.java
refactor/login -> main
회원 정보 수정 로직을 수정했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
> refactor: 회원정보수정 로직 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UpdateUserInfoRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/query/dto/response/UserInfoResponse.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/validator/PhoneValidator.java
- second-server/src/main/resources/mappers/user/UserMapper.xml
feat/user-rank -> main
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
이상 없음
> feat: 마이페이지 추가 정보 조회 기능

- second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/ErrorCode.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/controller/ImageController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/dto/request/SaveImageRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/service/ImageService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/image/service/ImageServiceImpl.java
feat/image-> main
게시판 기능 사용 시, 이미지 저장을 구현 했습니다!
> feat: 이미지 임시 저장, 저장 구현

- first-server/src/main/java/com/hanhwa_tae/firstserver/security/SecurityConfig.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/SecondServerApplication.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/security/SecurityConfig.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/me/query/controller/MyPageQueryController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/me/query/mapper/MyPageMapper.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/me/query/service/MyPageQueryService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/query/dto/response/UserBoardDTO.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/query/dto/response/UserBoardResponse.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/query/dto/response/UserCommentDTO.java
- second-server/src/main/resources/mappers/user/me/MyPageMapper.xml
fix/mypage-post -> main
마이페이지 내 게시글 조회 기능 수정
마이페이지 내 댓글 조회 기능 수정
포스트맨 테스트 완료
> Fix: 마이페이지 내 게시글 및 댓글 조회 수정

- .idea/dataSources.local.xml
- .idea/dataSources/63a39563-c0f5-4dce-970d-3313853a4041.xml
- .idea/dataSources/63a39563-c0f5-4dce-970d-3313853a4041/storage_v2/_src_/schema/information_schema.FNRwLQ.meta
- .idea/dataSources/c5b94fda-a51f-4f84-bc57-e4c7a64483a1.xml
- .idea/modules.xml
- .idea/modules/be15-2nd-baksal-gulhan.iml
- .idea/vcs.xml
- .idea/workspace.xml
- first-server/src/main/java/com/hanhwa_tae/firstserver/goods/command/domain/aggregate/Goods.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/goods/query/dto/response/GoodsDTO.java
- first-server/src/main/resources/mappers/goods/GoodsMapper.xml
- second-server/src/main/java/com/hanhwa_tae/secondserver/config/AwsConfig.java
refactor/packages-> main
제가 저번에 GoodsDTO를 잘못 수정했더라구요... query에 넣고 싶었는데 command 쪽에 들어가있었어요 다시 올립니다.
> refactor: GoodsDTO 수정

- .idea/workspace.xml
- first-server/src/main/resources/mappers/packages/PackageMapper.xml
> refactor: PackageMapper 오타 수정

- .idea/workspace.xml
- first-server/src/main/resources/mappers/packages/PackageMapper.xml
> refactor: PackageMapper area 필터링 조건

- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/application/controller/DeliveryCommandController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/application/dto/request/DeliveryAddressRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/application/service/DeliveryCommandService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/domain/aggregate/DeliveryAddress.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/command/domain/repository/DeliveryAddressRepository.java
fix/deliveryaddress -> main
배송지 수정, 삭제 기능을 수정했습니다.
정상
> fix: 배송지 수정, 삭제 기능 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/user/query/dto/response/UserCommentDTO.java
- second-server/src/main/resources/mappers/user/me/MyPageMapper.xml
fix/mypage-comment -> main
내 댓글 조회할때 댓글이 있는 게시글ID도 응답하게 수정했습니다
테스트 완료
> Fix: 마이페이지 내 댓글 응답 값 수정

- first-server/src/main/resources/mappers/goods/GoodsMapper.xml
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
> refactor: GoodsMapper.xml 수정

- first-server/src/main/resources/mappers/packages/PackageMapper.xml
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
> refactor: PackageMapper.xml 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/auth/command/application/controller/KakaoUserController.java
fix/kakao-login -> main
로그인 컨트롤러 수정
> fix: 카카오 로그인 기능 수정

- first-server/src/main/java/com/hanhwa_tae/firstserver/like/query/dto/response/LikeDto.java
- first-server/src/main/java/com/hanhwa_tae/firstserver/place/query/dto/response/PlacesDto.java
- first-server/src/main/resources/mappers/like/likeMapper.xml
- first-server/src/main/resources/mappers/place/PlaceMapper.xml
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
> 좋아요 백엔드 수정

- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/controller/DashboardQueryController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/dto/request/DashboardGoodsSearchRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/dto/request/DashboardOrderSearchRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/dto/request/DashboardPackageSearchRequest.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/dto/response/GoodsQuantityDTO.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/dto/response/OrderAllListDTO.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/user/query/dto/response/UserCommentResponse.java
- second-server/src/main/resources/mappers/dashboard/DashboardMapper.xml
fix/dashboard-order -> main
기존에 운송장번호 미입력된 내역만 불러온코드를 전체 다 불러오게 수정
대시보드 응답 값 수정
요청 다 잘 나옵니다~
> Fix: 대시보드 응답 값 수정 #183

- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/application/controller/DashboardCommandController.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/application/service/DashboardCommandService.java
- second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/query/mapper/DashboardOrderMapper.java
fix/dashboard-shipping
orderId String 으로 타입 변경
정상작동
> Fix: 대시보드 타입 변경 #193
